MariAzhdari/finalProject-HubPlanner

server/api.js
=> dotenv and  deploy to render.

client/src/App.js, client/src/components/Form.js, client/src/components/Login.js
=> Form and Login page created

client/src/components/Calendar.js, client/src/components/Main.js
=> Main.js & Calendar.js created

client/src/App.js, client/src/components/Login.js, client/src/components/login.css, client/src/index.html
=> login page just React and style done

client/src/pages/Attendance.js
=> #26-attendance table-Mickey Haile

client/src/App.js, client/src/pages/Attendance.js
=> #28-use state created-Mickey Haile

client/src/App.js, client/src/pages/Attendance.js
=>  #30-fetch and display-Mickey Haile

client/src/pages/TravelDisruption.js
=> #35-button to display disruption-Mickey HAILE

client/src/pages/TravelDisruption.js
=> #37-travel state-Mickey haile

client/src/components/Calendar.js
=> calendar.js 2

client/src/components/calendar.css
=> calendar.css

client/src/components/calendar.css
=> Elicalendar.css

client/src/App.js
=> App changed

client/src/App.js, client/src/components/Form.js, client/src/components/attendance.css, client/src/components/attendance.js
=> #47-attendencs design-Mickey Haile

client/src/App.js, client/src/components/Attendance.js
=> change the component name

client/src/App.js, client/src/components/Form.js
=> return the class name

client/src/App.js
=> App default

.dev, client/src/App.js, client/src/components/Attendance.css, client/src/components/Attendance.js
=> Attendance design page

package-lock.json, package.json, server/api.js, server/db.js, server/server.js, server/utils/middelware/authorize.js, server/utils/middelware/jwtGenerator.js
=> login endpoint

client/src/components/Form.js, package-lock.json, package.json, server/api.js
=> Mariformfront

client/src/components/Form.js, client/src/components/form.css, server/api.js
=> form just need test and add some futures

client/src/components/Attendance.js, client/src/components/attendance.css
=> Attendance.js updated

client/src/components/attendance.css
=>  Attendance.css updated

client/src/components/Attendance.js
=> Eli attendance page functionality

client/src/components/Attendance.js
=> all inputs functionality added

server/api.js
=> api.js - Fetch attendance data

server/api.js
=> Submit attendance data

client/src/components/Login.js, client/src/components/Main.js, client/src/pages/About.js, client/src/pages/Home.css, client/src/pages/Home.js, package-lock.json, package.json
=> login and form changes

client/src/components/Calendar.js, client/src/components/calendar.sql, server/api.js
=> Calendarmickey

client/src/components/Attendance.js, client/src/components/attendance.css, server/api.js
=> Eli attendance streach goals

client/src/components/TravelCheck.js
=> new branch test

client/src/components/TravelCheck.js, client/src/components/travelCheck.css, server/api.js
=> Marifinaltrevel

client/src/components/Calendar.js
=> syllabus links added

client/src/components/Attendance.js, client/src/components/attendance.css
=> Eli attendance stretch goals 

client/src/components/Calendar.js, client/src/components/Login.js, client/src/components/Main.js, client/src/components/TravelCheck.js, client/src/components/calendar.css, client/src/components/form.css, client/src/components/login.css, client/src/components/main.css, client/src/components/travelCheck.css
=> Maricsschecker

client/src/components/Form.js, server/api.js
=> register end point

client/src/components/Attendance.js, client/src/components/Breakout.js, client/src/components/attendance.css, client/src/components/breakout.css, client/src/components/main.css
=> Eli attendance css20

client/src/components/Attendance.js, client/src/components/Main.js, client/src/components/attendance.css, client/src/components/calendar.css, client/src/components/main.css, client/src/components/travelCheck.css
=> Eli final css

client/src/components/calendar.css
=> changes css

client/src/components/attendance.css
=> attendence css change

client/src/components/Calendar.js
=> navebar  change

server/api.js
=> cleaned up

client/src/components/calendar.css
=> calender css

client/src/components/Main.js, client/src/components/calendar.css, client/src/components/login.css, client/src/components/main.css, server/api.js
=> Lastdaychanges
